name: Generate GitHub Readme Stats

on:
  push:
    branches:
      - main  

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate GitHub Readme Stats
        uses: anuraghazra/github-readme-stats@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: liethdallal
          THEME: default

      - name: Commit and push changes
        run: |
          git config --global user.name 'Lieth Dallal'
          git config --global user.email 'liethdallal@gmail.com'
          git add README.md
          git commit -m 'Update README with GitHub Readme Stats'
          git push
